name: oyuncu_dukkani
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.2+13

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.5.3
  audioplayers: ^6.6.0
  google_mobile_ads: ^5.3.1
  device_info_plus: ^11.2.0
  app_tracking_transparency: ^2.0.6+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  device_preview: ^1.2.0
  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true  # Apple App Store şeffaflık (alpha kanal) kabul etmiyor
  image_path: "assets/oyuncu_dukkani_icon.png"
  adaptive_icon_background: "#000000"
  adaptive_icon_foreground: "assets/oyuncu_dukkani_icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/sounds/
    - assets/anamenu.png
    - assets/bg1.png
    - assets/bg2.png
    - assets/bgbos.png
    - assets/bgbos_2.jpg
    - assets/bgbos_3.jpg
    - assets/bgbos_4.jpg
    - assets/bgbosmasa.png
    - assets/biri.png
    - assets/browser.png
    - assets/durum.png
    - assets/hirsiz.png
    - assets/joypad.png
    - assets/kolonya.png
    - assets/kurye.png
    - assets/oyuncudireksiyonu.png
    - assets/oyuncu_dukkani_icon.png
    - assets/polis.png
    - assets/toptanci.png
    - assets/falci.png
    - assets/vergici.png
    - assets/3dgozluk.png
    - assets/gamepad.png
    - assets/lokum.png
    - assets/zarf.png
    - assets/konsol_1.png
    - assets/konsol_2.png
    - assets/konsol_3.png
    - assets/konsol_4.png
    - assets/konsol_5.png
    - assets/konsol_6.png
    - assets/konsol_7.png
    - assets/musteri_1.png
    - assets/musteri_2.png
    - assets/musteri_3.png
    - assets/musteri_4.png
    - assets/musteri_5.png
    - assets/musteri_6.png
    - assets/musteri_7.png
    - assets/musteri_8.png
    - assets/musteri_9.png
    - assets/musteri_10.png
    - assets/musteri_11.png
    - assets/musteri_12.png
    - assets/musteri_13.png
    - assets/musteri_14.png
    - assets/musteri_15.png
    - assets/musteri_16.png
    - assets/musteri_17.png
    - assets/musteri_18.png
    - assets/musteri_19.png
    - assets/musteri_20.png
    - assets/musteri_21.png
    - assets/musteri_22.png
    - assets/musteri_23.png
    - assets/musteri_24.png
    - assets/musteri_25.png
    - assets/musteri_26.png
    - assets/musteri_27.png
    - assets/musteri_28.png
    - assets/CD_1.png
    - assets/CD_2.png
    - assets/CD_3.png
    - assets/CD_4.png
    - assets/CD_5.png
    - assets/CD_6.png
    - assets/CD_7.png
    - assets/CD_8.png
    - assets/CD_9.png
    - assets/CD_10.png
    - assets/CD_11.png
    - assets/CD_12.png
    - assets/CD_13.png
    - assets/CD_14.png